name: Lint Action - JS

on: [push, pull_request]
defaults:
  run:
    working-directory: frontend
# jobs:
#   run-linters:
#     name: Run linters
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [12.x]

#     steps:
#       - name: Check out Git repository
#         uses: actions/checkout@v2

#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}

#       - name: Install dependencies
#         run: yarn install
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.GPR_AUTH_TOKEN }}
#           CI: true

#       - name: Run Build
#         run: yarn build

#       - name: Run Tests
#         run: yarn run test:ci

#       # ESLint and Prettier must be in `package.json`
#       - name: Run JavaScript linters
#         uses: wearerequired/lint-action@v1
#         with:
#           eslint: true
#           prettier: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Node.js dependencies
      uses: yarn install --frozen-lockfile
      # uses: npm ci / npm install

    # - name: Check build if present
    #   uses: npm run build --if-present

    - name: Run JavaScript linters
      uses: wearerequired/lint-action@v1
      with:
          eslint: true
          prettier: true
