name: Lint Action - JS

on: [push, pull_request]
defaults:
  run:
    working-directory: frontend2

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Node.js dependencies
      run: npm install
      # run: npm ci / npm install

    - name: Check build if present
      uses: npm run build --if-present

    - name: Run JavaScript linters
      uses: wearerequired/lint-action@v1
      with:
          eslint: true
          prettier: true
